### ISSUE TITLE
npm publish new version?

### ISSUE THREAD

**Issue by noffle** [ipfs/js-libp2p-ipfs#2]
It looks like there were some big API changes since the last version -- are they ready to be pushed to npm? Is the API fairly established at this point?

**Comment by diasdavid** [comment]
I feel pretty confident about the libp2p-swarm API, although I haven't got much reviews (not even at all), when it comes to routing and record store, that is the 'deferred' situation because of currently go-libp2p implementation differing from spec, expect some changes there.

**Comment by diasdavid** [comment]
Closing this issue as it is old now, there has been several other iterations. Next step is recreate js-libp2p as a base that libp2p-ipfs and libp2p-ipfs-browser can extend
